/**
 * Per-rule reference generator (spec §1.4, §10): emits docs/rules.md from the rule
 * registry so the docs can never drift from the code. Run: pnpm docs:rules
 */
import fs from 'node:fs';
import path from 'node:path';
import { RULES } from '../src/core/rules/rule-registry.js';

const OUT = path.resolve(import.meta.dirname, '../docs/rules.md');

const rules = [...RULES].sort((a, b) => a.id.localeCompare(b.id));

const lines: string[] = [];
lines.push(
  '<!-- GENERATED by `pnpm docs:rules` from src/core/rules/rule-registry.ts — do not edit by hand. -->',
);
lines.push('');
lines.push('# Rule Reference');
lines.push('');
lines.push(
  `API Guard ships **${rules.length} rules**. Every rule id is a configuration key in the ` +
    '`rules:`' +
    ' section of `apiguard.yaml`; every severity can be overridden per rule, and per context ' +
    'with the `ruleId@context` syntax (see the [configuration guide](configuration.md)).',
);
lines.push('');
lines.push('| Rule | Default severity | Default kind | Contexts |');
lines.push('|---|---|---|---|');
for (const r of rules) {
  lines.push(
    `| \`${r.id}\` | ${r.defaultSeverity} | ${r.defaultKind} | ${r.contexts.join(', ')} |`,
  );
}
lines.push('');
lines.push('## Details');
lines.push('');
for (const r of rules) {
  lines.push(`### \`${r.id}\``);
  lines.push('');
  lines.push(
    `- **Default severity:** ${r.defaultSeverity}${r.defaultSeverity === 'error' ? ' (breaking)' : ''}`,
  );
  lines.push(`- **Default kind:** ${r.defaultKind}`);
  lines.push(`- **Contexts:** ${r.contexts.join(', ')}`);
  lines.push(`- **Trigger:** ${r.trigger}`);
  // message/suggestion take the change; render with placeholder tokens
  lines.push(
    `- **Message template:** ${r.message.length > 0 ? '(see sample outputs below)' : 'static'}`,
  );
  lines.push('');
}

// sample output table for CI logs: render each rule with a synthetic change
lines.push('## Sample output');
lines.push('');
lines.push('Each rule renders a human message from the change it detects. Sample messages with');
lines.push('representative values:');
lines.push('');
lines.push('```');
for (const r of rules.slice(0, 25)) {
  const sample = {
    ruleId: r.id,
    severity: r.defaultSeverity,
    kind: r.defaultKind,
    breaking: r.defaultSeverity === 'error',
    message: '',
    suggestion: '',
    location: {
      path: '/users',
      method: 'GET',
      pointerOld: '#/paths/~1users/get',
      pointerNew: '#/paths/~1users/get',
      context: r.contexts[0] ?? 'operation',
    },
    oldValue: '"old"',
    newValue: '"new"',
    id: 'sample',
  };
  let message = '(context-dependent)';
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    message = (r.message as any)(sample) || message;
  } catch {
    // keep the fallback
  }
  lines.push(`${r.id}: ${message}`);
}
lines.push('```');
lines.push('');

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, lines.join('\n') + '\n', 'utf8');
console.log(`wrote ${OUT} (${rules.length} rules)`);
