/**
 * Registry parity tests (§23): docs/rules.md must be in sync with the rule registry,
 * and the registry itself must be well-formed (unique ids, valid enums, contexts).
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { RULES, getRule } from '../../src/core/rules/rule-registry.js';

const REPO_ROOT = path.resolve(import.meta.dirname, '../..');

describe('rule registry well-formedness (§23)', () => {
  it('has unique rule ids', () => {
    const ids = RULES.map((r) => r.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('every rule has valid severity, kind, and non-empty contexts/trigger/message', () => {
    for (const r of RULES) {
      expect(['error', 'warning', 'info'], r.id).toContain(r.defaultSeverity);
      expect(
        ['addition', 'removal', 'modification', 'relaxation', 'documentation'],
        r.id,
      ).toContain(r.defaultKind);
      expect(r.contexts.length, r.id).toBeGreaterThan(0);
      expect(r.trigger.length, r.id).toBeGreaterThan(0);
      expect(typeof r.message, r.id).toBe('function');
    }
  });

  it('getRule returns definitions and throws for unknown ids', () => {
    expect(getRule('removed-path').id).toBe('removed-path');
    expect(() => getRule('not-a-real-rule')).toThrow();
  });
});

describe('docs/rules.md parity (§23)', () => {
  const doc = readFileSync(path.join(REPO_ROOT, 'docs/rules.md'), 'utf8');

  it('mentions every rule id in the summary table', () => {
    for (const r of RULES) {
      expect(doc, `docs/rules.md missing rule ${r.id}`).toContain(`\`${r.id}\``);
    }
  });

  it('is marked as generated and states the rule count', () => {
    expect(doc).toContain('GENERATED by `pnpm docs:rules`');
    expect(doc).toContain(`**${RULES.length} rules**`);
  });
});
